package login;

import controlador.VistasControlador;
import placeholder.PlaceHolder;

public class LoginVista extends javax.swing.JFrame {
    
    /**
    * Creates new form Login
    * @param controlador
    * Hacemos dos placeHolders para los dos campos en los que escribira el usuario, txtUsuario y txtContraseña
    */  
    
    public LoginVista(VistasControlador controlador) { //No tocar
         
        initComponents();
        this.setVisible(true);
        new PlaceHolder(this.txtUsuario, "Ingresa tu usuario");
        btnIngresar.addActionListener(controlador);
        btnRegistro.addActionListener(controlador); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInterfaz = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        lbParteAltaLogin = new javax.swing.JLabel();
        lbParteBajaLogin = new javax.swing.JLabel();
        lbFondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInterfaz.setForeground(new java.awt.Color(204, 204, 204));
        jpInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpInterfaz.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 410, 40));
        jpInterfaz.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, 410, 40));

        btnIngresar.setBackground(new java.awt.Color(51, 204, 0));
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpInterfaz.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 340, 402, 40));

        btnRegistro.setBackground(new java.awt.Color(0, 204, 255));
        btnRegistro.setText("Registrarse");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpInterfaz.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 432, 130, 40));

        lbParteAltaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ParteAltaLogin.jpg"))); // NOI18N
        jpInterfaz.add(lbParteAltaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbParteBajaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ParteBajaLogin.png"))); // NOI18N
        jpInterfaz.add(lbParteBajaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        getContentPane().add(jpInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 450, 490));

        lbFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FondoLogin.jpg"))); // NOI18N
        getContentPane().add(lbFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jpInterfaz;
    private javax.swing.JLabel lbFondoLogin;
    private javax.swing.JLabel lbParteAltaLogin;
    private javax.swing.JLabel lbParteBajaLogin;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}