package login;

import controlador.VistasControlador;
import placeholder.PlaceHolder;
import javax.swing.JOptionPane;

public class RegistroVista extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVista
     * @param controlador
     */
    public RegistroVista(VistasControlador controlador) { //No tocar
        
        initComponents();
        this.setVisible(false);
        PlaceHolder holder = new PlaceHolder(this.txtUsuario, "Ej: ElPro1234");
        holder = new PlaceHolder(this.txtContraseña, "Ej: OmocatLLSPP");
        btnRegistrarse.addActionListener(controlador);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        lbIconoUsuario = new javax.swing.JLabel();
        lbParteAltaRegistro = new javax.swing.JLabel();
        lbParteBajaRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de jugador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, 40));

        btnRegistrarse.setBackground(new java.awt.Color(208, 55, 55));
        btnRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarse.setText("¡ Jugar Ya !");
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 293, 290, 40));

        lbIconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoUsuario.png"))); // NOI18N
        jPanel1.add(lbIconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 80, -1, -1));

        lbParteAltaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ParteAltaRegistro.png"))); // NOI18N
        jPanel1.add(lbParteAltaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbParteBajaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ParteBajaRegistro.png"))); // NOI18N
        jPanel1.add(lbParteBajaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIconoUsuario;
    private javax.swing.JLabel lbParteAltaRegistro;
    private javax.swing.JLabel lbParteBajaRegistro;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
