package menu;

import controlador.VistasControlador;

public class MenuVista extends javax.swing.JFrame {

    /**
     * Creates new form MenuVista
     * @param controlador
     */
    
    public MenuVista(VistasControlador controlador) {
        
        initComponents();
        this.setVisible(false);
        btnJugar.addActionListener(controlador);
        btnPuntuaciones.addActionListener(controlador);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnPuntuaciones = new javax.swing.JButton();
        lbFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tetris titulo.png"))); // NOI18N
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        btnJugar.setBackground(new java.awt.Color(0, 204, 255));
        btnJugar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(0, 0, 0));
        btnJugar.setText("Iniciar Juego");
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 300, 50));

        btnPuntuaciones.setBackground(new java.awt.Color(208, 55, 55));
        btnPuntuaciones.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPuntuaciones.setForeground(new java.awt.Color(0, 0, 0));
        btnPuntuaciones.setText("Registro de Puntos");
        btnPuntuaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnPuntuaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 300, 50));

        lbFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FondoLogin.jpg"))); // NOI18N
        jPanel1.add(lbFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnJugar;
    public javax.swing.JButton btnPuntuaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFondoMenu;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}